# Generated by Django 3.2.8 on 2021-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referido',
            name='data_agendamento',
            field=models.DateTimeField(blank=True),
        ),
    ]
