# Generated by Django 3.2.8 on 2021-10-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0002_alter_referido_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referido',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
