# Generated by Django 3.2.8 on 2021-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0003_alter_referido_data_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='referido',
            name='quem_indicou',
            field=models.CharField(default='Leandro', max_length=200),
        ),
    ]
