# Generated by Django 4.0.1 on 2022-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0005_alter_referido_quem_indicou'),
    ]

    operations = [
        migrations.AddField(
            model_name='referido',
            name='aluno',
            field=models.BooleanField(default=False),
        ),
    ]
