# Generated by Django 4.0.4 on 2022-05-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0006_referido_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('aluno', models.CharField(choices=[('Matriculou', 'Matriculou'), ('Não Matriculou', 'Não Matriculou')], default='Matriculou', max_length=200)),
            ],
        ),
    ]
