# Generated by Django 4.0.4 on 2022-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0008_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
