# Generated by Django 4.0.4 on 2022-05-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0009_delete_aluno_cliente_data_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(choices=[('Aluno', 'Aluno'), ('Não Aluno', 'Não Aluno')], default='Aluno', max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referidos.cliente')),
            ],
        ),
    ]
