# Generated by Django 4.0.4 on 2022-05-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0011_remove_aluno_cliente_alter_referido_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referido',
            name='quem_indicou',
        ),
    ]
