# Generated by Django 4.0.4 on 2022-05-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referidos', '0012_remove_referido_quem_indicou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referido',
            name='data_agendamento',
        ),
        migrations.AlterField(
            model_name='referido',
            name='prioridade',
            field=models.CharField(choices=[('Neutro', 'Neutro'), ('Sim', 'Sim'), ('Não', 'Não')], default='Neutro', max_length=200),
        ),
    ]
